layouts/partials/custom-header.html

Issue: https://github.com/FidelusAleksander/githubcertified/issues/56

Shuffle questions, global hardcoded quizdown config

---

.github/PULL_REQUEST_TEMPLATE.md
archetypes/questions.md
content/practice_tests/actions.md
content/practice_tests/admin.md
content/practice_tests/advanced_security.md
content/practice_tests/foundations.md
layouts/partials/archetypes/questions/article.html
layouts/partials/quizdown.html
layouts/shortcodes/practice_test.html

Quizdown code extracted to a partial

Extract quizdown

---

config/_default/outputs.toml
config/_default/params.toml

- Search bar
- Next/previous page buttons
- 
Search Bar
Previous/next page buttons

Update theme version to 5.23.1, enable searchbar

---

CONTRIBUTING.md
archetypes/questions.md

Updated contributing guide
https://github.com/FidelusAleksander/githubcertified/issues/77

Update CONTRIBUTING and the questions archetype

---

content/questions/actions/question-021.md

fix Q21 solution

---

.github/dependabot.yml

Fixed the configuration file for dependabot

Fix dependabot package-ecosystem

---

content/questions/actions/question-032.md
content/questions/actions/question-038.md
content/questions/actions/question-039.md

Fix links/typos in GitHub Actions questions

---

content/questions/advanced_security/question-002.md
content/questions/advanced_security/question-003.md
content/questions/advanced_security/question-004.md
content/questions/advanced_security/question-005.md
content/questions/advanced_security/question-006.md

New questions for the Github Advanced Security exam

GitHub Advanced Security questions

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/content_issue.md
.github/PULL_REQUEST_TEMPLATE.md

Updated issue/pr templates with proper comments
- 
If applicable

Update issue/pr templates with proper comments

---

content/questions/actions/question-074.md

- Q74 is a duplicate of Q60, so I updated it.
- 
If applicable

fix duplicate question

---

.github/labeler.yml
.github/workflows/label-pr.yml

Add labeler workflow

---

.github/dependabot.yml

Check for submodule updates with dependabot

Add checking submodule to dependabot

---

content/questions/advanced_security/question-007.md
content/questions/advanced_security/question-008.md
content/questions/advanced_security/question-009.md
content/questions/advanced_security/question-010.md
content/questions/advanced_security/question-011.md
content/questions/advanced_security/question-012.md

New questions for the GitHub Advanced Security exam

Add advanced security questions 7,8,9,10,11,12

---

content/questions/advanced_security/question-019.md
content/questions/advanced_security/question-020.md
content/questions/advanced_security/question-021.md
content/questions/advanced_security/question-022.md

Add new questions for the Advanced Security exam

Add advanced_security questions 19,20,20,21,22

---

content/questions/advanced_security/question-023.md
content/questions/advanced_security/question-024.md
content/questions/advanced_security/question-025.md
content/questions/advanced_security/question-026.md
content/questions/advanced_security/question-027.md
content/questions/advanced_security/question-028.md

New questions for the Advanced Security Exam

Add advanced security questions 23,24,25,26,27,28

---

content/practice_tests/_index.md
content/practice_tests/advanced_security.md
content/questions/advanced_security/question-029.md
content/questions/advanced_security/question-030.md
content/questions/advanced_security/question-031.md

- Add more questions for Advanced Security exam
- Enable the Advanced Security practice test

Advanced security/add questions 4

---

content/_index.md

Add legal disclaimer to Home Page

Add legal disclaimer

---

content/questions/foundations/question-002.md
content/questions/foundations/question-003.md
content/questions/foundations/question-004.md
content/questions/foundations/question-005.md
content/questions/foundations/question-006.md
content/questions/foundations/question-007.md
content/questions/foundations/question-008.md
content/questions/foundations/question-009.md
content/questions/foundations/question-010.md
content/questions/foundations/question-011.md
content/questions/foundations/question-012.md
content/questions/foundations/question-013.md
content/questions/foundations/question-014.md
content/questions/foundations/question-015.md
content/questions/foundations/question-016.md
content/questions/foundations/question-017.md

Tried to cover all topics in the **Domain 5: Project Management**  from GitHub's study guide
https://github.com/FidelusAleksander/githubcertified/issues/90

[Domain 5: Project Management] Add questions for the GitHub Foundations exam 

---

.github/ISSUE_TEMPLATE/content_issue.md
.github/ISSUE_TEMPLATE/content_request.md
.github/ISSUE_TEMPLATE/feature_request.md

Update issue templates

---

.github/workflows/label-pr.yml

Labeler workflow will remove labels when matching files are reverted or no longer changed by the pull_request

Enable sync-labels for labeler

---

content/questions/foundations/question-035.md
content/questions/foundations/question-036.md
content/questions/foundations/question-037.md
content/questions/foundations/question-038.md
content/questions/foundations/question-039.md
content/questions/foundations/question-040.md
content/questions/foundations/question-041.md
content/questions/foundations/question-042.md
content/questions/foundations/question-043.md
content/questions/foundations/question-044.md
content/questions/foundations/question-045.md
content/questions/foundations/question-046.md
content/questions/foundations/question-047.md
content/questions/foundations/question-048.md
content/questions/foundations/question-049.md
content/questions/foundations/question-050.md
content/questions/foundations/question-051.md
content/questions/foundations/question-052.md
content/questions/foundations/question-053.md

Tried to cover all topics in the **Domain 6: Privacy, Security, and Administration** from GitHub's study guide
https://github.com/FidelusAleksander/githubcertified/issues/90

Add Foundations questions about Authentication and Security

---

content/questions/foundations/question-054.md
content/questions/foundations/question-055.md
content/questions/foundations/question-056.md
content/questions/foundations/question-057.md
content/questions/foundations/question-058.md
content/questions/foundations/question-059.md
content/questions/foundations/question-060.md
content/questions/foundations/question-061.md
content/questions/foundations/question-062.md
content/questions/foundations/question-063.md
content/questions/foundations/question-064.md

Tried to cover all topics in the **Domain 7: Benefits of the GitHub Community**  from GitHub's study guide
https://github.com/FidelusAleksander/githubcertified/issues/90

[Domain 7: Benefits of the GitHub Community  ] Add Foundations questions q54-q64

---

content/questions/foundations/question-065.md
content/questions/foundations/question-066.md
content/questions/foundations/question-067.md
content/questions/foundations/question-068.md
content/questions/foundations/question-069.md
content/questions/foundations/question-070.md
content/questions/foundations/question-071.md
content/questions/foundations/question-072.md
content/questions/foundations/question-073.md
content/questions/foundations/question-074.md
content/questions/foundations/question-075.md
content/questions/foundations/question-076.md
content/questions/foundations/question-077.md
content/questions/foundations/question-078.md
content/questions/foundations/question-079.md
content/questions/foundations/question-080.md
content/questions/foundations/question-081.md
content/questions/foundations/question-082.md
content/questions/foundations/question-083.md
content/questions/foundations/question-084.md
content/questions/foundations/question-085.md
content/questions/foundations/question-086.md
content/questions/foundations/question-087.md

Tried to cover all topics in the **Domain 1: Introduction to Git and GitHub ** from GitHub's study guide
https://github.com/FidelusAleksander/githubcertified/issues/90

[Domain 1: Introduction to Git and GitHub] Add Foundations exam questions 

---

content/questions/foundations/question-088.md
content/questions/foundations/question-089.md
content/questions/foundations/question-090.md
content/questions/foundations/question-091.md
content/questions/foundations/question-092.md
content/questions/foundations/question-093.md
content/questions/foundations/question-094.md
content/questions/foundations/question-095.md
content/questions/foundations/question-096.md
content/questions/foundations/question-097.md
content/questions/foundations/question-098.md

Partial coverage of Domain 3: Collaboration Features

---

content/practice_tests/foundations.md

Shuffle questions/answers in Foundations exam as it was missing

Fix: add shuffling to foundations practice exam

---

content/questions/foundations/question-002.md
content/questions/foundations/question-004.md
content/questions/foundations/question-005.md
content/questions/foundations/question-008.md
content/questions/foundations/question-017.md
content/questions/foundations/question-034.md
content/questions/foundations/question-037.md
content/questions/foundations/question-042.md
content/questions/foundations/question-060.md
content/questions/foundations/question-073.md
content/questions/foundations/question-074.md
content/questions/foundations/question-086.md
content/questions/foundations/question-091.md
content/questions/foundations/question-094.md

Fixing typos in questions for GitHub Foundations exam

Fixing typos in questions for GitHub Foundations exam

---

content/questions/advanced_security/question-010.md
content/questions/advanced_security/question-025.md
content/questions/advanced_security/question-028.md

various fixes for GHAS questions

---

content/questions/advanced_security/question-032.md
content/questions/advanced_security/question-033.md
content/questions/advanced_security/question-034.md
content/questions/advanced_security/question-035.md
content/questions/advanced_security/question-036.md
content/questions/advanced_security/question-037.md
content/questions/advanced_security/question-038.md
content/questions/advanced_security/question-039.md
content/questions/advanced_security/question-040.md
content/questions/advanced_security/question-041.md

Add advanced security questions 32-41

---

content/questions/advanced_security/question-042.md
content/questions/advanced_security/question-043.md
content/questions/advanced_security/question-044.md
content/questions/advanced_security/question-045.md
content/questions/advanced_security/question-046.md
content/questions/advanced_security/question-047.md
content/questions/advanced_security/question-048.md
content/questions/advanced_security/question-049.md
content/questions/advanced_security/question-050.md

Add new GHAS questions

---

content/questions/advanced_security/question-010.md
content/questions/advanced_security/question-022.md
content/questions/advanced_security/question-031.md
content/questions/advanced_security/question-037.md
content/questions/advanced_security/question-041.md

Small fixes in GHAS questions

---

content/questions/advanced_security/question-063.md
content/questions/advanced_security/question-064.md
content/questions/advanced_security/question-065.md
content/questions/advanced_security/question-066.md
content/questions/advanced_security/question-067.md
content/questions/advanced_security/question-068.md
content/questions/advanced_security/question-069.md
content/questions/advanced_security/question-070.md
content/questions/advanced_security/question-071.md
content/questions/advanced_security/question-072.md

Covered the first block  (Explain how CodeQL enables code scanning) in **Domain 5: Use code scanning with CodeQL**

Add GHAS questions for part  of Domain 5

---

content/questions/advanced_security/question-073.md
content/questions/advanced_security/question-074.md
content/questions/advanced_security/question-075.md
content/questions/advanced_security/question-076.md
content/questions/advanced_security/question-077.md
content/questions/advanced_security/question-078.md
content/questions/advanced_security/question-079.md
content/questions/advanced_security/question-080.md

Add more GHAS questions for Domain 5

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
CONTRIBUTING.md
README.md

Added devcontainers configuration to allow easy contributions through GitHub Codespaces.
Based devcontainers configuration from [microsoft examples ](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/hugo/.devcontainer/devcontainer.json)
Closes: https://github.com/FidelusAleksander/githubcertified/issues/111

Add devcontainers configuration file

---

.gitignore

Added 1 file to .gitignore
- [ x] Other
Added 1 file to .gitignore

Add nohup.out to .gitignore

---

layouts/shortcodes/practice_test.html

When doing a  practice exam clicking on a link will open it in a new tab
Closes: https://github.com/FidelusAleksander/githubcertified/issues/143

Open links in new tab when doing practice exams

---

config/_default/params.toml
content/practice_tests/_index.md
content/practice_tests/actions.md
content/practice_tests/admin.md
content/practice_tests/advanced_security.md
content/practice_tests/foundations.md
content/questions/_index.md
content/study_resources/_index.md

Update meta tags for SEO

---

content/practice_tests/actions.md
content/practice_tests/admin.md
content/practice_tests/advanced_security.md
content/practice_tests/foundations.md
content/questions/_index.md
content/questions/actions/_index.md
content/questions/admin/_index.md
content/questions/advanced_security/_index.md
content/questions/foundations/_index.md
content/study_resources/_index.md

Change html meta tags again

---

content/questions/advanced_security/question-081.md
content/questions/advanced_security/question-082.md
content/questions/advanced_security/question-083.md
content/questions/advanced_security/question-084.md
content/questions/advanced_security/question-085.md
content/questions/advanced_security/question-086.md
content/questions/advanced_security/question-087.md
content/questions/advanced_security/question-088.md
content/questions/advanced_security/question-089.md
content/questions/advanced_security/question-090.md

Third PR regarding **Domain 5: Use code scanning with CodeQL**. All (or most) topics should be covered by atleast 1 question

Finish GHAS Domain 5: Use code scanning with CodeQL

---

content/questions/advanced_security/question-091.md
content/questions/advanced_security/question-092.md
content/questions/advanced_security/question-093.md
content/questions/advanced_security/question-094.md
content/questions/advanced_security/question-095.md
content/questions/advanced_security/question-096.md
content/questions/advanced_security/question-097.md
content/questions/advanced_security/question-098.md

More questions for the GHAS exam
Focused on **Domain 7: GitHub Advanced Security Administration** from the study guide

Add GHAS questions for Domain 7

---

README.md
content/_index.md

breaking: Add information about the domain/repo name change

---

CONTRIBUTING.md
README.md
config/_default/hugo.toml
config/_default/menu.toml
config/_default/params.toml
content/_index.md
content/practice_tests/_index.md
content/questions/_index.md
layouts/partials/menu-footer.html

Repository will be renamed from githubcertified to ghcertified together with this change

Replace githubcertified with ghcertified in all occurrences

---

README.md

Smaller img in README

---

content/practice_tests/actions.md
content/practice_tests/admin.md
content/practice_tests/advanced_security.md
content/practice_tests/foundations.md
layouts/shortcodes/practice_test.html
layouts/shortcodes/test_cards.html

Rename practice test param to not be cofused with question param

---

content/practice_tests/actions.md
content/practice_tests/admin.md
content/practice_tests/advanced_security.md
content/practice_tests/foundations.md
content/questions/admin/question-002.md
layouts/partials/quizdown.html
layouts/shortcodes/practice_test.html
layouts/shortcodes/test_cards.html

Hack to allow taking exams with N questions
Initially done by in https://github.com/FidelusAleksander/ghcertified/pull/157 
https://github.com/FidelusAleksander/ghcertified/issues/144

Allow exams with N questions

---

.github/workflows/pr-checks.yml
content/questions/advanced_security/question-099.md
content/questions/advanced_security/question-100.md
content/questions/advanced_security/question-101.md
content/questions/advanced_security/question-102.md
content/questions/advanced_security/question-103.md
content/questions/advanced_security/question-104.md
content/questions/advanced_security/question-105.md
content/questions/advanced_security/question-106.md
content/questions/advanced_security/question-107.md
content/questions/advanced_security/question-108.md
content/questions/advanced_security/question-109.md
content/questions/advanced_security/question-110.md
content/questions/advanced_security/question-111.md
cspell.json

1. Fixed cspell action as it was not scanning content files
2. Added GHAS practice exam questions, tried to cover questions from **Domain 3: Configure and use dependency management** that were not previously covered
https://github.com/FidelusAleksander/ghcertified/issues/88

Add GHAS questions about Dependency Management

---

static/images/favicon.svg

Crop whitespace around favicon

Crop favicon whitespace

---

content/questions/advanced_security/question-014.md
content/questions/advanced_security/question-027.md
content/questions/advanced_security/question-031.md
content/questions/advanced_security/question-033.md
content/questions/advanced_security/question-047.md
content/questions/advanced_security/question-053.md
content/questions/advanced_security/question-054.md
content/questions/advanced_security/question-059.md
content/questions/advanced_security/question-062.md
content/questions/advanced_security/question-073.md
content/questions/advanced_security/question-074.md
content/questions/advanced_security/question-082.md
content/questions/advanced_security/question-099.md
content/questions/foundations/question-015.md

Fixing typo's / incorrect answers in GHAS questions

---

content/questions/foundations/question-062.md

Add number of answers to Foundations q62
Closes: https://github.com/FidelusAleksander/ghcertified/issues/180

Add number of answers to Foundations q62

---

content/questions/advanced_security/question-112.md
content/questions/advanced_security/question-113.md
content/questions/advanced_security/question-114.md

Three questions about CVSS/CVE/CWE
https://github.com/FidelusAleksander/ghcertified/issues/88

Add GHAS questions about CVSS

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
content/questions/actions/question-076.md

Added new question in GitHub Actions (Question 076) using https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations as reference / source.
Removed trailing ` from the CONTRIBUTING.md file
Removed trailing ` from PULL_REQUEST_TEMPLATE.md file

GHA Action Question & template fix

---

content/questions/actions/question-056.md

Fixing a word duplication in question 56 for GitHub Actions.

Fix typo in GHA  question 56

---

content/study_resources/_index.md

- Updated study guide links
- Added ExamPro course
- Added official LinkedIn GHAS course

Update study resources

---

content/practice_tests/_index.md
content/practice_tests/admin.md

Enable Github Admin exam

---

content/questions/admin/question-067.md
content/questions/admin/question-068.md
content/questions/admin/question-069.md
content/questions/admin/question-070.md
content/questions/admin/question-071.md
content/questions/admin/question-072.md
content/questions/admin/question-073.md
content/questions/admin/question-074.md
content/questions/admin/question-075.md
content/questions/admin/question-076.md
content/questions/admin/question-077.md
content/questions/admin/question-078.md
content/questions/admin/question-079.md
content/questions/admin/question-080.md
content/questions/admin/question-081.md
content/questions/admin/question-082.md
content/questions/admin/question-083.md
content/questions/admin/question-084.md
content/questions/admin/question-085.md
content/questions/admin/question-086.md
content/questions/admin/question-087.md
content/questions/admin/question-088.md
content/questions/admin/question-089.md
content/questions/admin/question-090.md
content/questions/admin/question-091.md
content/questions/admin/question-092.md
content/questions/admin/question-093.md
content/questions/admin/question-094.md
content/questions/admin/question-095.md

https://github.com/FidelusAleksander/ghcertified/issues/89

add Admin questions

---

content/questions/foundations/question-023.md

Update to a question on CoPilot Free Usage
Updated question in response to #200 
NA
N/A

Updated Question 23 in Foundations for free usage of CoPilot

---

content/questions/actions/question-077.md

Add one question (077) to Actions.
[#117](https://github.com/FidelusAleksander/ghcertified/issues/117)

Add 1 question to Actions

---

content/questions/foundations/question-023.md
content/questions/foundations/question-076.md
content/questions/foundations/question-110.md
content/questions/foundations/question-111.md

- Clarified question 76.
- Added two new questions.
https://github.com/FidelusAleksander/ghcertified/issues/214

Added and Clarified Pricing Plan Question(s)

---

content/questions/foundations/question-099.md

- One of the duplicated alternative was changed
#217

fix: Modify duplicated alternative

---

content/questions/actions/question-078.md

Added question 078 to actions

---

content/study_resources/_index.md

Add new resource for Github Actions Certificate. Youtube Video playlist made by ExamPro.
A new youtube playlist link has been added under Study Resources > "other free resources" for a youtube playlist for the Github Actions Certificate, its made by the ExamPro team.

Update Study Resources w/ new free resource

---

content/study_resources/_index.md

Update GHA study guide link

---

content/questions/foundations/question-038.md
content/questions/foundations/question-094.md

https://github.com/FidelusAleksander/ghcertified/issues/231
https://github.com/FidelusAleksander/ghcertified/discussions/232

Fix link and unclear answer in Foundations exam

---

content/questions/foundations/question-105.md

Fix answers for pulse question. Additions and deletions are shown but unresolved conversations are not shown. See screenshot

Fix pulse question

---

content/questions/actions/question-096.md
content/questions/actions/question-097.md
content/questions/actions/question-098.md
content/questions/actions/question-099.md
content/questions/actions/question-100.md
content/questions/actions/question-101.md

https://github.com/FidelusAleksander/ghcertified/issues/117

New questions to Github Actions

---

content/questions/foundations/question-021.md

Change foundations q21 link

---

content/questions/admin/question-019.md

The question said "a managed user account" and I updated it to say "an enterprise Managed Users account" to clarify that it's an EMU question.

Clarify EMUs in the question

---

.github/workflows/preview-site.yml

Started working on a new workflow that could help with PR reviews by creating preview environments

GHA workflow for cf pages preview deployments

---

.github/workflows/preview-site.yml

Change event trigger to pull_request_target

---

content/questions/actions/question-054.md
content/questions/actions/question-072.md
content/questions/actions/question-076.md
content/questions/actions/question-101.md
content/questions/actions/question-108.md

Fixed some typos and updated answer for GitHub Actions question 108.
#265

Fixed typos and updated answer

---

content/questions/admin/question-066.md

Fix title for question 66

---

content/questions/actions/question-014.md

Content Update
Fix: Corrected the answer to Q14 in GitHub Actions from 'no' to 'yes' .
This update resolves [#281](https://github.com/FidelusAleksander/ghcertified/issues/281) in the repository.

Fix: Change answer to Q14 in GitHub Actions to 'yes' instead of 'no

---

content/questions/actions/question-116.md

Fixed error "Single Choice questions can not have more than one correct answer.. App could not render. Please check your quizdown syntax." that was caused by question 116 from the Actions category.

Fixed markdown for Actions question 116

---

.devcontainer/devcontainer.json

Copilot now enabled in GitHub Codespaces launched in this repository

Add copilot to repository Codespaces

---

.github/labeler.yml

Automatically label new copilot content

Add copilot label to labeler file

---

content/questions/foundations/question-024.md

Fixed the link for GitHub Foundations Question 024
#292

Fixed the link for GitHub Foundations Question 024

---

content/questions/actions/question-003.md
content/questions/foundations/question-024.md

Add the link for GitHub Actions Question 003

Add the link for GitHub Actions Quesion 003

---

.github/workflows/pr-checks.yml

ci: Update cspell action config

---

.github/copilot-instructions.md
content/questions/copilot/question-010.md
content/questions/copilot/question-011.md
content/questions/copilot/question-012.md
content/questions/copilot/question-013.md

New copilot questions q10-q13

---

content/questions/copilot/question-014.md
content/questions/copilot/question-015.md
content/questions/copilot/question-016.md

New questions (q14-q16) related to GitHub Copilot.

Add GitHub Copilot questions q14-q16

---

content/questions/actions/question-123.md

First of all - thanks for the great tool and learning resource! Have been using it to help solidify my knowledge! 
Adds a question about accessing and cloning private repositories as a GitHub Workflow checkout step.
I briefly GREP'd / skimmed the existing content and didn't see anything on this exact topic although it seems like a fairly commonly encountered config step.
With `hugo_0.124.0_windows-amd64`:
Thanks!

docs: add q 123

---

content/questions/admin/question-059.md

Added correct link about github app manager aligned with the question, instead of github teams

Correct link update question-059.md

---

content/questions/admin/question-091.md

adding more appropriate sources to support the answer - #307

---

.devcontainer/devcontainer.json
.github/workflows/preview-site.yml
.github/workflows/test-build.yml
CONTRIBUTING.md
config/_default/hugo.toml
config/_default/outputs.toml
config/_default/params.toml
content/_index.md
content/practice_tests/_index.md
content/questions/advanced_security/question-014.md
cspell.json
layouts/questions/views/article.html

chore: update hugo to v0.145.0 and hugo-theme-relearn to 7.6.1

---

.github/copilot-instructions.md
.github/workflows/copilot-setup-steps.yml

Configure copilot coding agent

---

content/en/questions/copilot/question-027.md
content/en/questions/copilot/question-028.md
content/en/questions/copilot/question-029.md
content/en/questions/copilot/question-030.md
content/en/questions/copilot/question-031.md
content/en/questions/copilot/question-032.md

Added six new questions related to the GitHub Copilot exam
#290

feat: add questions 027 to 032 for GitHub Copilot practice test

---

content/en/questions/actions/question-121.md
content/pl/questions/actions/question-121.md
content/pt/questions/actions/question-121.md

https://github.com/FidelusAleksander/ghcertified/issues/365

feat: add a better reference link for actions q121 about default variables

---

.github/workflows/auto-translate.yml
.github/workflows/manual-bulk-translate.yml
config/_default/languages.toml

chore: setup workflows and config to include Spanish translation

---

content/en/questions/actions/question-127.md

feat: add GitHub Actions q127 about setting env variables with workflow commands

---

content/pt/questions/foundations/question-024.md
content/pt/questions/foundations/question-025.md
content/pt/questions/foundations/question-026.md
content/pt/questions/foundations/question-032.md
content/pt/questions/foundations/question-040.md
content/pt/questions/foundations/question-057.md
content/pt/questions/foundations/question-058.md
content/pt/questions/foundations/question-059.md
content/pt/questions/foundations/question-066.md
content/pt/questions/foundations/question-070.md
content/pt/questions/foundations/question-083.md
content/pt/questions/foundations/question-085.md
content/pt/questions/foundations/question-099.md
content/pt/questions/foundations/question-110.md
content/pt/questions/foundations/question-121.md
content/pt/questions/foundations/question-127.md
content/pt/questions/foundations/question-131.md
content/pt/questions/foundations/question-135.md
content/pt/questions/foundations/question-136.md
content/pt/questions/foundations/question-140.md
content/pt/questions/foundations/question-141.md
content/pt/questions/foundations/question-142.md
content/pt/questions/foundations/question-145.md

i18n(pt): translate remaining foundation questions to PT

---

content/es/questions/admin/question-033.md
content/pl/questions/_index.md
content/pl/questions/actions/question-055.md
content/pl/questions/admin/question-002.md
content/pl/questions/foundations/question-026.md
content/pl/questions/foundations/question-038.md
content/pl/questions/foundations/question-081.md

chore: minor translation fixes

---

content/en/questions/actions/question-013.md

Updated link to documentation that provide the right answer.

Update link for question about job dependencies
