.github/workflows/link-checker.yml

Add a gh workflow that checks all external links daily and creates issues if any are not working
Fixes: https://github.com/FidelusAleksander/githubcertified/issues/48

Add link checker action

---

.github/dependabot.yml

Remove submodule from dependabot as it always wants to update to latest commit, which may be unstable.
Tag granularity not supported 
https://github.com/dependabot/dependabot-core/issues/1639

Remove submodule dependabot as it doesnt support tag granularity

---

layouts/partials/quizdown.html

Questions in question tab were not shuffled, therefore the first answers were always correct

fix: Shuffle answers as default so they are shuffled in questions tab

---

content/questions/advanced_security/question-027.md

Removing duplicate answer: `When a commit is pushed to the default branch of your repository`

Update Q27 for GHAS

---

content/questions/advanced_security/question-007.md

Current question has two possible correct answers and not too much clear.

Update Q7 for GHAS

---

content/questions/_index.md

Make the sections the Contributed Questions page expandable

Add expandable sections in Contributed Questions page

---

content/_index.md
layouts/shortcodes/library-links.html
layouts/shortcodes/test_cards.html

When working on Codespaces the permalinks were redirecting to localhost instead of the codespace domain

Change Permalinks to RelPermalinks

---

content/study_resources/_index.md

Updated links to study guides, added LI course for GH Actions

Update study resources

---

content/questions/actions/question-018.md

fixed a typo in Actions Q18
The answers mentioned `/release` however the code sample showed `/releases`

fix answer to question-018 - releases/release inconsistant

---

config/_default/menu.toml

Side menu now has extra link/icon leading to [GitHub Discussions](https://github.com/FidelusAleksander/ghcertified/discussions)

Add menu item for GitHub Discussions

---

content/questions/foundations/question-099.md
content/questions/foundations/question-112.md
content/questions/foundations/question-113.md

- Added two questions about markdown

New questions about markdown in foundations test

---

content/questions/admin/question-003.md
content/questions/admin/question-004.md
content/questions/admin/question-005.md
content/questions/admin/question-007.md
content/questions/admin/question-012.md
content/questions/admin/question-038.md
content/questions/admin/question-075.md
content/questions/admin/question-096.md
cspell.json

New question related to rate-limiting. 
Update url's of existing admin question so they don't need to be updated when newer versions are released of GitHub components.

Admin question + url improvements for existing admin questions

---

content/questions/actions/question-116.md

Fixing the question 116 answer.
- Change the answer type from multi select option to unique choice. 
- Remove "When workflow run is two weeks old" from good answers.
- Adapt question sentence.
[Issue 252](https://github.com/FidelusAleksander/ghcertified/issues/252).
No screenshots.

fix #252 - update outdated answer

---

.github/workflows/preview-site.yml

Pull requests can now be labeled with `request-review-deployment` to trigger a preview cloudflare build

Preview deployments on labeled pull requests

---

content/questions/advanced_security/question-017.md
content/questions/advanced_security/question-074.md

Fixing outdated answers and links that were raised as an issue by @carlos-quintero
https://github.com/FidelusAleksander/ghcertified/issues/263
https://github.com/FidelusAleksander/ghcertified/issues/262

Fix answers and links in advanced security Q17 and Q74

---

.github/workflows/comment-new-issue.yaml

New workflow to inform issue creators that new features are stopped for near future due to my unavailability

Add issue comment workflow

---

content/questions/actions/question-014.md
content/questions/actions/question-116.md

PR Type
content changes (updating questions, answers, explanations or study resources)
What's new?
This PR corrects the answer for the 116th question, as it previously listed only one correct answer. 
The question now has two correct options.
Screenshots

correcting the 116th question answer (suppose to be two correct options)

---

.pre-commit-config.yaml
CONTRIBUTING.md
content/questions/copilot/question-002.md

New emulation question for GHCP certification exam. Partially addressing Issue #290.
- New question about GHCP 
- Minor edit on CONTRIBUTING.md file.
- (deps) pre-commit-hooks from v4.5.0 to v5.0.0.
- 
N/A

New GHCP question

---

CONTRIBUTING.md
content/questions/copilot/question-004.md
content/questions/copilot/question-005.md
content/questions/copilot/question-006.md
content/questions/copilot/question-007.md
content/questions/copilot/question-008.md
content/questions/copilot/question-009.md
content/study_resources/_index.md

This pull request includes several changes, primarily focused on adding new questions about GitHub Copilot and updating the contributing guidelines. The most important changes include the addition of new questions related to GitHub Copilot and the modification of the contributing guidelines to improve clarity.
* [`content/questions/copilot/question-004.md`](diffhunk://#diff-4381f4bb43cbb5feae53759dcfe4ffc1c728be88a0264a214455b9f7bb69f870R1-R13): Added a new question about the command used to install the GitHub Copilot extension on the CLI.
* [`content/questions/copilot/question-005.md`](diffhunk://#dif …

Add Community exam prep threads as Study Resources

---

content/questions/actions/question-124.md

Adds a new question about using matrix in GitHub Actions. The repo already has some questions on matrix, but this one focuses on the include key, specifically a case where one of the include entries overlaps with what's already defined in the main matrix.
I came up with this question after recently passing the certification — I didn’t copy it from the test, just recreated it knowing that the key part was to make "include" match an occurrence of the matrix. After the exam, I asked ChatGPT about it, but the answer it gave was wrong, so I ran the scenario myself to double-check the correct behavior.

add question 124 for github actions

---

.github/instructions/markdown-style.instructions.md
config/_default/menu.toml
content/en/_index.md
content/en/study_resources/_index.md
content/pl/_index.md
content/pl/study_resources/_index.md
content/pt/_index.md
content/pt/study_resources/_index.md

GitHub Certification page and GitHub Skills moved to new **learn** domain. This PR updates relevant links

Update GitHub learn links
